### ISSUE TITLE
【疑问】建议增加一个默认预测图（可根据胜率来分析的）

### ISSUE THREAD

**Issue by Sandu1213** [DreamAndDead/playoff-prediction#1]
先大胆的放出我的预测：
![image](https://user-images.githubusercontent.com/21214285/38789299-07a69552-416c-11e8-8244-221adce2a504.png)

参考地址：
https://dreamanddead.github.io/playoff-prediction/?map=424234414143414243242442344334

压上我五毛钱的辣条~~😄

**Comment by DreamAndDead** [comment]
目前看来虽然过程曲折，但东西部决赛还是比较准的（除了76ers）...

**Comment by DreamAndDead** [comment]
骑士输了总决，心疼
